alias dc="docker compose"
alias dcb="docker compose build"
alias dcbnc="docker compose build --no-cache"
alias dcdn="docker compose down"
alias dcdnv="docker compose down -v"
alias dce="docker compose exec"
alias dcl="docker compose logs"
alias dclf="docker compose logs -f"
alias dcps="docker compose ps"
alias dcr="docker compose run"
alias dcrestart="docker compose restart"
alias dcup="docker compose up"
alias dcupd="docker compose up -d"
alias dcupdf="docker compose up -d --force-recreate"

alias dps="docker ps"
alias dk="docker kill"
