alias c="claude"
alias cat="bat -p"
alias code="claude"
alias dot="cd ~/.dotfiles/"
alias hey="oha" # https://github.com/rakyll/hey/issues/269
alias l="eza -la --icons --no-permissions --no-user"
alias la="eza -la --icons"
alias ll="eza -l --icons"
alias ls="eza --icons"
alias lt="eza --tree --icons --level=2"
alias md="mkdir -p"
alias j="jsonnet"
alias jb="jsonnet-bundler"
alias sc="source ${HOME}/.zshrc"
alias watch="viddy"

alias pn="pnpm"
alias pna="pnpm add"
alias pni="pnpm install"
alias pnr="pnpm run"
alias pnrm="pnpm remove"
alias pnx="pnpx"

alias ta="tmux switch-client -t"
alias tks="tmux kill-session -t"
alias tkv="tmux kill-server"
alias tl="tmux list-sessions"
alias ts="tmux new-session -s"
