alias tg="terragrunt"
alias tga="terragrunt apply --non-interactive"
alias tgd="terragrunt destroy"
alias tgi="terragrunt import"
alias tgp="terragrunt plan --non-interactive"
alias tgrm="terragrunt state rm --non-interactive"
alias tgfd="fd -HI .terragrunt-cache --type d -X rm -rf"

alias tgra="terragrunt run --all --non-interactive -- apply"
alias tgrd="terragrunt run --all -- destroy"
alias tgri="terragrunt run --all -- init -upgrade"
alias tgrp="terragrunt run --all --non-interactive -- plan"

alias tgsa="terragrunt stack run --non-interactive -- apply"
alias tgsd="terragrunt stack run -- destroy"
alias tgsi="terragrunt stack run -- init -upgrade"
alias tgsp="terragrunt stack run --non-interactive -- plan"
